### ISSUE TITLE
Doesn't build, am I doing something wrong?

### ISSUE THREAD

**Issue by epoberezkin** [dosx/node-vips#8]
node_modules/vips$ make

node-gyp configure
gyp info it worked if it ends with ok
gyp info using node-gyp@0.9.5
gyp info using node@0.8.22 | linux | ia32
gyp info spawn python
gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/opt/nginx/html/dev.sheeporpig/node_modules/vips/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/eugene/.node-gyp/0.8.22/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/eugene/.node-gyp/0.8.22',
gyp info spawn args   '-Dmodule_root_dir=/opt/nginx/html/dev.sheeporpig/node_modules/vips',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok 
node-gyp build
gyp info it worked if it ends with ok
gyp info using node-gyp@0.9.5
gyp info using node@0.8.22 | linux | ia32
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make[1]: Entering directory `/opt/nginx/html/dev.sheeporpig/node_modules/vips/build'
  CXX(target) Release/obj.target/vips/src/node-vips.o
../src/node-vips.cc: In function ‘v8::Handle<v8::Value><unnamed>::ResizeAsync(const v8::Arguments&)’:
../src/node-vips.cc:133: error: invalid conversion from ‘void (*)(uv_work_t*, int)’ to ‘void (*)(uv_work_t*)’
../src/node-vips.cc:133: error:   initializing argument 4 of ‘int uv_queue_work(uv_loop_t*, uv_work_t*, void (*)(uv_work_t*), void (*)(uv_work_t*))’
../src/node-vips.cc: In function ‘v8::Handle<v8::Value><unnamed>::RotateAsync(const v8::Arguments&)’:
../src/node-vips.cc:153: error: invalid conversion from ‘void (*)(uv_work_t*, int)’ to ‘void (*)(uv_work_t*)’
../src/node-vips.cc:153: error:   initializing argument 4 of ‘int uv_queue_work(uv_loop_t*, uv_work_t*, void (*)(uv_work_t*), void (*)(uv_work_t*))’
../src/node-vips.cc: In function ‘v8::Handle<v8::Value><unnamed>::PngPixelAsync(const v8::Arguments&)’:
../src/node-vips.cc:229: error: invalid conversion from ‘void (*)(uv_work_t*, int)’ to ‘void (*)(uv_work_t*)’
../src/node-vips.cc:229: error:   initializing argument 4 of ‘int uv_queue_work(uv_loop_t*, uv_work_t*, void (*)(uv_work_t*), void (*)(uv_work_t*))’
make[1]: *** [Release/obj.target/vips/src/node-vips.o] Error 1
make[1]: Leaving directory`/opt/nginx/html/dev.sheeporpig/node_modules/vips/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:99:17)
gyp ERR! stack     at Process._handle.onexit (child_process.js:678:10)
gyp ERR! System Linux 3.7.10-linode49
gyp ERR! command "node" "/usr/local/bin/node-gyp" "build"
gyp ERR! cwd /opt/nginx/html/dev.sheeporpig/node_modules/vips
gyp ERR! node -v v0.8.22
gyp ERR! node-gyp -v v0.9.5
gyp ERR! not ok 
make: **\* [compile] Error 1

**Comment by eden** [comment]
I haven't tried this on Linux 0.8. Is it possible for you to try this with
node 0.10?

**Comment by epoberezkin** [comment]
I also thought node 0.8.22 might be a problem, but I would really like to postpone the upgrade for at least 2 months (production/development sites are on one server at the moment)...
But looking at error log it seems that it's c code that creates problems. I don't think node has anything to do with it, it's not used to build it, is it?
Maybe I have some old compiler version installed (although I've just updated packages)? Or maybe, on the opposite, I should install an older version of node-gyp (it says node > 0.6 though)?
I should admit that's my lack of experience most likely...
Thanks!

**Comment by eden** [comment]
Looks like node 0.10 changed the definition of `uv_after_work_cb`. I pushed a fix that I can't easily test. Can you pull and retry?

**Comment by epoberezkin** [comment]
Definitely, I am on it, I need this library... Thanks!

**Comment by epoberezkin** [comment]
It still fails but differently this time, so we are making progress here!
It complains about not being able to find exiv2. I have it installed as both a sibling (I did it when make didn't even start), globally and as a dependency (it didn't help either). It's not listed as dependency in package.json by the way ...
Maybe it's the wrong exiv2? I installed it with "npm install exiv2".

node-gyp configure
gyp info it worked if it ends with ok
gyp info using node-gyp@0.9.5
gyp info using node@0.8.22 | linux | ia32
gyp info spawn python
gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/opt/nginx/html/dev.sheeporpig/node_modules/vips/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/eugene/.node-gyp/0.8.22/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/eugene/.node-gyp/0.8.22',
gyp info spawn args   '-Dmodule_root_dir=/opt/nginx/html/dev.sheeporpig/node_modules/vips',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok 
node-gyp build
gyp info it worked if it ends with ok
gyp info using node-gyp@0.9.5
gyp info using node@0.8.22 | linux | ia32
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make[1]: Entering directory `/opt/nginx/html/dev.sheeporpig/node_modules/vips/build'
  CXX(target) Release/obj.target/vips/src/transform.o
../src/transform.cc:40:27: warning: exiv2/exiv2.hpp: No such file or directory
../src/transform.cc: In destructor ‘ImageFreer::~ImageFreer()’:
../src/transform.cc:64: error: ‘uint16_t’ was not declared in this scope
../src/transform.cc:64: error: expected ‘;’ before ‘i’
../src/transform.cc:64: error: ‘i’ was not declared in this scope
../src/transform.cc: In function ‘int GetEXIFRotationNeeded(const std::string&, std::string*)’:
../src/transform.cc:91: error: ‘Exiv2’ has not been declared
../src/transform.cc:91: error: expected ‘;’ before ‘image’
../src/transform.cc:92: error: ‘image’ was not declared in this scope
../src/transform.cc:94: error: ‘Exiv2’ has not been declared
../src/transform.cc:94: error: ‘ed’ was not declared in this scope
../src/transform.cc:95: error: ‘Exiv2’ has not been declared
../src/transform.cc:95: error: expected ‘;’ before ‘it’
../src/transform.cc:97: error: ‘it’ was not declared in this scope
../src/transform.cc:106: error: expected type-specifier before ‘Exiv2’
../src/transform.cc:106: error: expected ‘)’ before ‘::’ token
../src/transform.cc:106: error: expected ‘{’ before ‘::’ token
../src/transform.cc:106: error: ‘::Error’ has not been declared
../src/transform.cc:106: error: ‘e’ was not declared in this scope
../src/transform.cc:106: error: expected ‘;’ before ‘)’ token
../src/transform.cc: At global scope:
../src/transform.cc:130: error: ‘uint16_t’ has not been declared
../src/transform.cc: In function ‘int WriteEXIFOrientation(const std::string&, int)’:
../src/transform.cc:132: error: ‘Exiv2’ has not been declared
../src/transform.cc:132: error: expected ‘;’ before ‘image’
../src/transform.cc:133: error: ‘image’ was not declared in this scope
../src/transform.cc:138: error: expected type-specifier before ‘Exiv2’
../src/transform.cc:138: error: expected ‘)’ before ‘::’ token
../src/transform.cc:138: error: expected ‘{’ before ‘::’ token
../src/transform.cc:138: error: ‘::Error’ has not been declared
../src/transform.cc:138: error: ‘e’ was not declared in this scope
../src/transform.cc:138: error: expected ‘;’ before ‘)’ token
../src/transform.cc: In function ‘void InitTransform(const char*)’:
../src/transform.cc:340: error: ‘Exiv2’ has not been declared
make[1]: *** [Release/obj.target/vips/src/transform.o] Error 1
make[1]: Leaving directory`/opt/nginx/html/dev.sheeporpig/node_modules/vips/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:99:17)
gyp ERR! stack     at Process._handle.onexit (child_process.js:678:10)
gyp ERR! System Linux 3.7.10-linode49
gyp ERR! command "node" "/usr/local/bin/node-gyp" "build"
gyp ERR! cwd /opt/nginx/html/dev.sheeporpig/node_modules/vips
gyp ERR! node -v v0.8.22
gyp ERR! node-gyp -v v0.9.5
gyp ERR! not ok 
make: **\* [compile] Error 1

**Comment by eden** [comment]
Yeah, it depends on the C++ library exiv2 _not_ the node package (which is why it isn't in package.json). You'll need a newer version of exiv2 (the one I tested was 0.23).

If you're on ubuntu, try https://launchpad.net/ubuntu/+source/exiv2

**Comment by epoberezkin** [comment]
I am on debian squeeze. I have it installed (both the library and command line tool), but stable version: http://packages.debian.org/squeeze/exiv2 . Am I right that I have to put the source of 0.23 (http://packages.debian.org/source/sid/exiv2) into the "exiv2" subfolder of vips?

**Comment by eden** [comment]
You'll have to install it from source probably. I'm not sure how Debian handles non-mainline packages. The Makefile won't install it for you as it assumes you have it on your system already.

**Comment by epoberezkin** [comment]
I can do it, that's not a problem, but from error log it looks like it cannot find headers file in subfolder:

../src/transform.cc:40:27: warning: exiv2/exiv2.hpp: No such file or directory

So just reinstalling newer version will not be enough probably. I think it may even work with the version I have... But where do I get this headers file?...

**Comment by eden** [comment]
The header file will be installed from the newest version of exiv2. Assuming it's installed correctly, the include path will find this in your system's include directory, _not_ the local directory.

Older versions of exiv2 don't have this file.

**Comment by epoberezkin** [comment]
Got it. Sorry for stupid questions.

**Comment by epoberezkin** [comment]
We are making progress here :) I installed newer version of exiv2, it was happy until it failed to find some other file:

...

npm install --dev
npm http GET https://registry.npmjs.org/imagemagick
npm http 200 https://registry.npmjs.org/imagemagick
npm http GET https://registry.npmjs.org/imagemagick/-/imagemagick-0.1.3.tgz
npm http 200 https://registry.npmjs.org/imagemagick/-/imagemagick-0.1.3.tgz

> vips@0.0.11 install /opt/nginx/html/dev.sheeporpig/node_modules/vips
> node-gyp rebuild

make[1]: Entering directory `/opt/nginx/html/dev.sheeporpig/node_modules/vips/build'
  CXX(target) Release/obj.target/vips/src/node-vips.o
  CXX(target) Release/obj.target/vips/src/transform.o
  SOLINK_MODULE(target) Release/obj.target/vips.node
  SOLINK_MODULE(target) Release/obj.target/vips.node: Finished
  COPY Release/vips.node
make[1]: Leaving directory`/opt/nginx/html/dev.sheeporpig/node_modules/vips/build'
imagemagick@0.1.3 node_modules/imagemagick

module.js:485
  process.dlopen(filename, module.exports);
          ^
Error: libexiv2.so.12: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (module.js:485:11)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/opt/nginx/html/dev.sheeporpig/node_modules/vips/index.js:5:20)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
make: **\* [test] Error 1

Thanks again!

**Comment by eden** [comment]
That's just for the test. It doesn't use imagemagick anywhere else. You can
try using the module now.

On Thu, May 2, 2013 at 12:10 PM, Eugene Poberezkin <notifications@github.com

**Comment by epoberezkin** [comment]
You are right, this is the message from simple-test.js, not from build (just checked :)
So I will start using it. Thank you very much!
